#!/bin/python
import sys

# void _isr0();

# idt_set_gate(0, _isr0, 0x08, IDT_FLAG_INTERUPT_GATE_32 | IDT_FLAG_RING_0);

def main():
    
    with_error = [8, 10, 11, 12, 13, 14, 17, 21]
    
    if len(sys.argv) != 2: 
        print(f"usage: {sys.argv[0]} [asm/c]")
        return

    if sys.argv[1] == "asm":
        print("; !!!!! THIS IS AN AUTOGENERATED FILE !!!!!\n")
        for i in range(256):
            if i in with_error: print(f"ISR_ERROR {i}")
            else: print(f"ISR_NO_ERROR {i}")
            
    if sys.argv[1] == "c":
        print("// !!!!! THIS IS AN AUTOGENERATED FILE !!!!!\n")
        print("#include \"i686/idt.h\"")
        print("#include \"i686/isr.h\"\n")
       
        for i in range(256):
            print(f"void _isr{i}();")
       
        print("\nvoid isr_install()\n{")
        for i in range(256):
            print(f"    idt_set_gate({i}, (uint32_t)_isr{i}, 0x08, IDT_FLAG_INTERUPT_GATE_32 | IDT_FLAG_RING_0 | IDT_FLAG_PRESENT);")
        print("}")
    

if __name__ == "__main__":
    main()