import sys
from PIL import Image

if len(sys.argv) < 2:
    print(f"usage: {sys.argv[0]} <image.png> [var_name]", file=sys.stderr)
    sys.exit(1)

path     = sys.argv[1]
var_name = sys.argv[2] if len(sys.argv) >= 3 else "image"

img = Image.open(path).convert("RGBA")
w, h = img.size

print(f"// !!!!! THIS IS AN AUTOGENERATED FILE !!!!!\n")
print(f"#pragma once")
print(f"#include <stdint.h>")
print(f"#define {var_name.upper()}_WIDTH  {w}")
print(f"#define {var_name.upper()}_HEIGHT {h}")
print(f"static uint32_t {var_name}_data[] = {{")

for y in range(h):
    for x in range(w):
        r, g, b, a = img.getpixel((x, y))
        pixel = (a << 24) | (r << 16) | (g << 8) | b
        print(f"    0x{pixel:08X},")

print(f"}};")